### ISSUE TITLE
appendCSS Error

### ISSUE THREAD

**Issue by JuLiAnChz** [ucsdmath/Pdf#1]
Hi, i use your interface from mPDF in my Laravel Project, but i have an error :
FatalThrowableError in AbstractPdfAdapter.php line 627: Fatal error: Call to undefined method mPDF::WriteCSS()

I use this:
use UCSDMath\Pdf\Pdf;
$mPdf = new Pdf ();
$mPdf->initializePageSetup ();
$mPdf->appendPageCSS ('.table {border: 1px solid black;}');
$mPdf->appendPageContent (view ('pdf));
$mPdf->render ();

**Comment by ucsdmath** [comment]
Hi Julián,
I added the correct method to fix the PDF/CSS issue.
So for now we can use the dev-master copy until 1.7.0 is released.

```
With the following:
    "require": {
        "ucsdmath/functions": "dev-master",
        "ucsdmath/pdf": "dev-master"
    }
```

This works now:
```
<?php
error_reporting(E_ERROR);
require('vendor/autoload.php');
use UCSDMath\Pdf\Pdf;

$mPdf = new Pdf();
$mPdf->initializePageSetup();
$mPdf->appendPageCSS('.special {color: green;}');
$mPdf->appendPageContent('<p class="special">Hello World!</p>');
$mPdf->render();
```

Thanks for commenting on my error referencing the _**mPDF**_ method

**Comment by JuLiAnChz** [comment]
Thx! :+1:
