### ISSUE TITLE
setFooter does not work

### ISSUE THREAD

**Issue by JuLiAnChz** [ucsdmath/Pdf#2]
Hi bro,
I use setFooter and this does not work, but before updating (yesterday), it worked properly.

EDIT:
this is my code:

`$mPdf->setFooter ([
			'left' => '{PAGENO} / {nbpg}',
			'center' => $InternalCompany->bill_footer.'<br><i>Impreso por MedIntegral - Software Médico Integral</i>'
		]);`

EDIT2: this is the difference between the two

`array(2) {
  ["odd"]=>
  array(4) {
    [0]=>
    array(1) {
      ["L"]=>
      array(5) {
        ["content"]=>
        string(34) "{PAGENO} / {nbpg}"
        ["font-size"]=>
        int(9)
        ["font-style"]=>
        string(0) ""
        ["font-family"]=>
        string(5) "Arial"
        ["color"]=>
        string(7) "#000000"
      }
    }
    [1]=>
    array(1) {
      ["C"]=>
      array(5) {
        ["content"]=>
        string(156) "Favor aplicar retención del 2% e ICA del 6.6 x 1000 si es de la misma ciudad
Impreso por MedIntegral - Software Médico Integral"
        ["font-size"]=>
        int(9)
        ["font-style"]=>
        string(0) ""
        ["font-family"]=>
        string(5) "Arial"
        ["color"]=>
        string(7) "#000000"
      }
    }
    [2]=>
    array(1) {
      ["R"]=>
      array(5) {
        ["content"]=>
        string(17) ""
        ["font-size"]=>
        int(9)
        ["font-style"]=>
        string(0) ""
        ["font-family"]=>
        string(5) "Arial"
        ["color"]=>
        string(7) "#000000"
      }
    }
    ["line"]=>
    bool(true)
  }
  ["even"]=>
  array(0) {
  }
}

PDF Before

array(2) {
  ["odd"]=>
  array(4) {
    ["L"]=>
    array(5) {
      ["content"]=>
      string(17) ""
      ["font-size"]=>
      int(9)
      ["font-style"]=>
      string(0) ""
      ["font-family"]=>
      string(5) "Arial"
      ["color"]=>
      string(7) "#000000"
    }
    ["C"]=>
    array(5) {
      ["content"]=>
      string(17) ""
      ["font-size"]=>
      int(9)
      ["font-style"]=>
      string(1) "I"
      ["font-family"]=>
      string(5) "Arial"
      ["color"]=>
      string(7) "#000000"
    }
    ["R"]=>
    array(5) {
      ["content"]=>
      string(17) ""
      ["font-size"]=>
      int(9)
      ["font-style"]=>
      string(0) ""
      ["font-family"]=>
      string(5) "Arial"
      ["color"]=>
      string(7) "#000000"
    }
    ["line"]=>
    bool(true)
  }
  ["even"]=>
  array(0) {
  }
}
`

**Comment by JuLiAnChz** [comment]
The issue persists

**Comment by ucsdmath** [comment]
Hi Julian,

Sorry for taking so long.  Try the patch update:  ucsdmath/pdf  1.8.1  or just update to the latest stable.  Let me know if that works for you or if you run into any issues.
Thank you,
Daryl
